  const ADD_TO_CART = 'ADD_TO_CART';
  const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
  const REMOVE_ALL_CART = "REMOVE_ALL_CART";
  const FETCH_BOOK = "FETCH_BOOK";
  

 export {ADD_TO_CART,REMOVE_ALL_CART,REMOVE_FROM_CART,FETCH_BOOK}



